pipeline:
  build:
    image: node:carbon
    commands:
      - make install
      - make test
  
steps:
- name: docker  
  image: plugins/docker
  settings:
    username: prasadaws143
    password: Volley@143
    repo: prasadaws143/athieriot/drone-artifactory 
    tags: latest
